// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "ecat_data_t.h"

static int __ecat_data_t_hash_computed;
static uint64_t __ecat_data_t_hash;

uint64_t __ecat_data_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ecat_data_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __ecat_data_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x2dd37f039d5cbafcLL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ecat_data_t_get_hash(void)
{
    if (!__ecat_data_t_hash_computed) {
        __ecat_data_t_hash = (int64_t)__ecat_data_t_hash_recursive(NULL);
        __ecat_data_t_hash_computed = 1;
    }

    return __ecat_data_t_hash;
}

int __ecat_data_t_encode_array(void *buf, int offset, int maxlen, const ecat_data_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].x, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].y, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].z, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].fx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].fy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].fz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].q_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].q_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].q_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dq_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dq_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dq_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_des_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_des_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_des_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].loop_count_ti, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].ethercat_count_ti, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].microtime_ti, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ecat_data_t_encode(void *buf, int offset, int maxlen, const ecat_data_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ecat_data_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ecat_data_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __ecat_data_t_encoded_array_size(const ecat_data_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(p[element].x, 4);

        size += __float_encoded_array_size(p[element].y, 4);

        size += __float_encoded_array_size(p[element].z, 4);

        size += __float_encoded_array_size(p[element].dx, 4);

        size += __float_encoded_array_size(p[element].dy, 4);

        size += __float_encoded_array_size(p[element].dz, 4);

        size += __float_encoded_array_size(p[element].fx, 4);

        size += __float_encoded_array_size(p[element].fy, 4);

        size += __float_encoded_array_size(p[element].fz, 4);

        size += __float_encoded_array_size(p[element].q_abad, 4);

        size += __float_encoded_array_size(p[element].q_hip, 4);

        size += __float_encoded_array_size(p[element].q_knee, 4);

        size += __float_encoded_array_size(p[element].dq_abad, 4);

        size += __float_encoded_array_size(p[element].dq_hip, 4);

        size += __float_encoded_array_size(p[element].dq_knee, 4);

        size += __float_encoded_array_size(p[element].tau_abad, 4);

        size += __float_encoded_array_size(p[element].tau_hip, 4);

        size += __float_encoded_array_size(p[element].tau_knee, 4);

        size += __float_encoded_array_size(p[element].tau_des_abad, 4);

        size += __float_encoded_array_size(p[element].tau_des_hip, 4);

        size += __float_encoded_array_size(p[element].tau_des_knee, 4);

        size += __int16_t_encoded_array_size(p[element].loop_count_ti, 4);

        size += __int16_t_encoded_array_size(p[element].ethercat_count_ti, 4);

        size += __int16_t_encoded_array_size(p[element].microtime_ti, 4);

    }
    return size;
}

int ecat_data_t_encoded_size(const ecat_data_t *p)
{
    return 8 + __ecat_data_t_encoded_array_size(p, 1);
}

int __ecat_data_t_decode_array(const void *buf, int offset, int maxlen, ecat_data_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].x, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].y, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].z, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].fx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].fy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].fz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].q_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].q_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].q_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dq_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dq_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dq_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_des_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_des_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_des_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].loop_count_ti, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].ethercat_count_ti, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].microtime_ti, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ecat_data_t_decode_array_cleanup(ecat_data_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(p[element].x, 4);

        __float_decode_array_cleanup(p[element].y, 4);

        __float_decode_array_cleanup(p[element].z, 4);

        __float_decode_array_cleanup(p[element].dx, 4);

        __float_decode_array_cleanup(p[element].dy, 4);

        __float_decode_array_cleanup(p[element].dz, 4);

        __float_decode_array_cleanup(p[element].fx, 4);

        __float_decode_array_cleanup(p[element].fy, 4);

        __float_decode_array_cleanup(p[element].fz, 4);

        __float_decode_array_cleanup(p[element].q_abad, 4);

        __float_decode_array_cleanup(p[element].q_hip, 4);

        __float_decode_array_cleanup(p[element].q_knee, 4);

        __float_decode_array_cleanup(p[element].dq_abad, 4);

        __float_decode_array_cleanup(p[element].dq_hip, 4);

        __float_decode_array_cleanup(p[element].dq_knee, 4);

        __float_decode_array_cleanup(p[element].tau_abad, 4);

        __float_decode_array_cleanup(p[element].tau_hip, 4);

        __float_decode_array_cleanup(p[element].tau_knee, 4);

        __float_decode_array_cleanup(p[element].tau_des_abad, 4);

        __float_decode_array_cleanup(p[element].tau_des_hip, 4);

        __float_decode_array_cleanup(p[element].tau_des_knee, 4);

        __int16_t_decode_array_cleanup(p[element].loop_count_ti, 4);

        __int16_t_decode_array_cleanup(p[element].ethercat_count_ti, 4);

        __int16_t_decode_array_cleanup(p[element].microtime_ti, 4);

    }
    return 0;
}

int ecat_data_t_decode(const void *buf, int offset, int maxlen, ecat_data_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ecat_data_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ecat_data_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ecat_data_t_decode_cleanup(ecat_data_t *p)
{
    return __ecat_data_t_decode_array_cleanup(p, 1);
}

int __ecat_data_t_clone_array(const ecat_data_t *p, ecat_data_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(p[element].x, q[element].x, 4);

        __float_clone_array(p[element].y, q[element].y, 4);

        __float_clone_array(p[element].z, q[element].z, 4);

        __float_clone_array(p[element].dx, q[element].dx, 4);

        __float_clone_array(p[element].dy, q[element].dy, 4);

        __float_clone_array(p[element].dz, q[element].dz, 4);

        __float_clone_array(p[element].fx, q[element].fx, 4);

        __float_clone_array(p[element].fy, q[element].fy, 4);

        __float_clone_array(p[element].fz, q[element].fz, 4);

        __float_clone_array(p[element].q_abad, q[element].q_abad, 4);

        __float_clone_array(p[element].q_hip, q[element].q_hip, 4);

        __float_clone_array(p[element].q_knee, q[element].q_knee, 4);

        __float_clone_array(p[element].dq_abad, q[element].dq_abad, 4);

        __float_clone_array(p[element].dq_hip, q[element].dq_hip, 4);

        __float_clone_array(p[element].dq_knee, q[element].dq_knee, 4);

        __float_clone_array(p[element].tau_abad, q[element].tau_abad, 4);

        __float_clone_array(p[element].tau_hip, q[element].tau_hip, 4);

        __float_clone_array(p[element].tau_knee, q[element].tau_knee, 4);

        __float_clone_array(p[element].tau_des_abad, q[element].tau_des_abad, 4);

        __float_clone_array(p[element].tau_des_hip, q[element].tau_des_hip, 4);

        __float_clone_array(p[element].tau_des_knee, q[element].tau_des_knee, 4);

        __int16_t_clone_array(p[element].loop_count_ti, q[element].loop_count_ti, 4);

        __int16_t_clone_array(p[element].ethercat_count_ti, q[element].ethercat_count_ti, 4);

        __int16_t_clone_array(p[element].microtime_ti, q[element].microtime_ti, 4);

    }
    return 0;
}

ecat_data_t *ecat_data_t_copy(const ecat_data_t *p)
{
    ecat_data_t *q = (ecat_data_t*) malloc(sizeof(ecat_data_t));
    __ecat_data_t_clone_array(p, q, 1);
    return q;
}

void ecat_data_t_destroy(ecat_data_t *p)
{
    __ecat_data_t_decode_array_cleanup(p, 1);
    free(p);
}

int ecat_data_t_publish(lcm_t *lc, const char *channel, const ecat_data_t *p)
{
      int max_data_size = ecat_data_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ecat_data_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _ecat_data_t_subscription_t {
    ecat_data_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void ecat_data_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    ecat_data_t p;
    memset(&p, 0, sizeof(ecat_data_t));
    status = ecat_data_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ecat_data_t!!!\n", status);
        return;
    }

    ecat_data_t_subscription_t *h = (ecat_data_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ecat_data_t_decode_cleanup (&p);
}

ecat_data_t_subscription_t* ecat_data_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    ecat_data_t_handler_t f, void *userdata)
{
    ecat_data_t_subscription_t *n = (ecat_data_t_subscription_t*)
                       malloc(sizeof(ecat_data_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 ecat_data_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg ecat_data_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ecat_data_t_subscription_set_queue_capacity (ecat_data_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int ecat_data_t_unsubscribe(lcm_t *lcm, ecat_data_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ecat_data_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

