// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "ecat_command_t.h"

static int __ecat_command_t_hash_computed;
static uint64_t __ecat_command_t_hash;

uint64_t __ecat_command_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ecat_command_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __ecat_command_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xad03831ee9458f34LL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ecat_command_t_get_hash(void)
{
    if (!__ecat_command_t_hash_computed) {
        __ecat_command_t_hash = (int64_t)__ecat_command_t_hash_recursive(NULL);
        __ecat_command_t_hash_computed = 1;
    }

    return __ecat_command_t_hash;
}

int __ecat_command_t_encode_array(void *buf, int offset, int maxlen, const ecat_command_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].x_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].y_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].z_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dx_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dy_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].dz_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kpx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kpy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kpz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kdx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kdy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kdz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, p[element].enable, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, p[element].zero_joints, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].fx_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].fy_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].fz_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_abad_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_hip_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tau_knee_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].abad_zero_angle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].hip_zero_angle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].knee_zero_angle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].q_des_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].q_des_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].q_des_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].qd_des_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].qd_des_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].qd_des_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kp_joint_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kp_joint_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kp_joint_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kd_joint_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kd_joint_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].kd_joint_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].max_torque, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ecat_command_t_encode(void *buf, int offset, int maxlen, const ecat_command_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ecat_command_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ecat_command_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __ecat_command_t_encoded_array_size(const ecat_command_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(p[element].x_des, 4);

        size += __float_encoded_array_size(p[element].y_des, 4);

        size += __float_encoded_array_size(p[element].z_des, 4);

        size += __float_encoded_array_size(p[element].dx_des, 4);

        size += __float_encoded_array_size(p[element].dy_des, 4);

        size += __float_encoded_array_size(p[element].dz_des, 4);

        size += __float_encoded_array_size(p[element].kpx, 4);

        size += __float_encoded_array_size(p[element].kpy, 4);

        size += __float_encoded_array_size(p[element].kpz, 4);

        size += __float_encoded_array_size(p[element].kdx, 4);

        size += __float_encoded_array_size(p[element].kdy, 4);

        size += __float_encoded_array_size(p[element].kdz, 4);

        size += __int32_t_encoded_array_size(p[element].enable, 4);

        size += __int32_t_encoded_array_size(p[element].zero_joints, 4);

        size += __float_encoded_array_size(p[element].fx_ff, 4);

        size += __float_encoded_array_size(p[element].fy_ff, 4);

        size += __float_encoded_array_size(p[element].fz_ff, 4);

        size += __float_encoded_array_size(p[element].tau_abad_ff, 4);

        size += __float_encoded_array_size(p[element].tau_hip_ff, 4);

        size += __float_encoded_array_size(p[element].tau_knee_ff, 4);

        size += __float_encoded_array_size(p[element].abad_zero_angle, 4);

        size += __float_encoded_array_size(p[element].hip_zero_angle, 4);

        size += __float_encoded_array_size(p[element].knee_zero_angle, 4);

        size += __float_encoded_array_size(p[element].q_des_abad, 4);

        size += __float_encoded_array_size(p[element].q_des_hip, 4);

        size += __float_encoded_array_size(p[element].q_des_knee, 4);

        size += __float_encoded_array_size(p[element].qd_des_abad, 4);

        size += __float_encoded_array_size(p[element].qd_des_hip, 4);

        size += __float_encoded_array_size(p[element].qd_des_knee, 4);

        size += __float_encoded_array_size(p[element].kp_joint_abad, 4);

        size += __float_encoded_array_size(p[element].kp_joint_hip, 4);

        size += __float_encoded_array_size(p[element].kp_joint_knee, 4);

        size += __float_encoded_array_size(p[element].kd_joint_abad, 4);

        size += __float_encoded_array_size(p[element].kd_joint_hip, 4);

        size += __float_encoded_array_size(p[element].kd_joint_knee, 4);

        size += __float_encoded_array_size(p[element].max_torque, 4);

    }
    return size;
}

int ecat_command_t_encoded_size(const ecat_command_t *p)
{
    return 8 + __ecat_command_t_encoded_array_size(p, 1);
}

int __ecat_command_t_decode_array(const void *buf, int offset, int maxlen, ecat_command_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].x_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].y_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].z_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dx_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dy_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].dz_des, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kpx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kpy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kpz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kdx, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kdy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kdz, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, p[element].enable, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, p[element].zero_joints, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].fx_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].fy_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].fz_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_abad_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_hip_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tau_knee_ff, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].abad_zero_angle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].hip_zero_angle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].knee_zero_angle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].q_des_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].q_des_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].q_des_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].qd_des_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].qd_des_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].qd_des_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kp_joint_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kp_joint_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kp_joint_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kd_joint_abad, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kd_joint_hip, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].kd_joint_knee, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].max_torque, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ecat_command_t_decode_array_cleanup(ecat_command_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(p[element].x_des, 4);

        __float_decode_array_cleanup(p[element].y_des, 4);

        __float_decode_array_cleanup(p[element].z_des, 4);

        __float_decode_array_cleanup(p[element].dx_des, 4);

        __float_decode_array_cleanup(p[element].dy_des, 4);

        __float_decode_array_cleanup(p[element].dz_des, 4);

        __float_decode_array_cleanup(p[element].kpx, 4);

        __float_decode_array_cleanup(p[element].kpy, 4);

        __float_decode_array_cleanup(p[element].kpz, 4);

        __float_decode_array_cleanup(p[element].kdx, 4);

        __float_decode_array_cleanup(p[element].kdy, 4);

        __float_decode_array_cleanup(p[element].kdz, 4);

        __int32_t_decode_array_cleanup(p[element].enable, 4);

        __int32_t_decode_array_cleanup(p[element].zero_joints, 4);

        __float_decode_array_cleanup(p[element].fx_ff, 4);

        __float_decode_array_cleanup(p[element].fy_ff, 4);

        __float_decode_array_cleanup(p[element].fz_ff, 4);

        __float_decode_array_cleanup(p[element].tau_abad_ff, 4);

        __float_decode_array_cleanup(p[element].tau_hip_ff, 4);

        __float_decode_array_cleanup(p[element].tau_knee_ff, 4);

        __float_decode_array_cleanup(p[element].abad_zero_angle, 4);

        __float_decode_array_cleanup(p[element].hip_zero_angle, 4);

        __float_decode_array_cleanup(p[element].knee_zero_angle, 4);

        __float_decode_array_cleanup(p[element].q_des_abad, 4);

        __float_decode_array_cleanup(p[element].q_des_hip, 4);

        __float_decode_array_cleanup(p[element].q_des_knee, 4);

        __float_decode_array_cleanup(p[element].qd_des_abad, 4);

        __float_decode_array_cleanup(p[element].qd_des_hip, 4);

        __float_decode_array_cleanup(p[element].qd_des_knee, 4);

        __float_decode_array_cleanup(p[element].kp_joint_abad, 4);

        __float_decode_array_cleanup(p[element].kp_joint_hip, 4);

        __float_decode_array_cleanup(p[element].kp_joint_knee, 4);

        __float_decode_array_cleanup(p[element].kd_joint_abad, 4);

        __float_decode_array_cleanup(p[element].kd_joint_hip, 4);

        __float_decode_array_cleanup(p[element].kd_joint_knee, 4);

        __float_decode_array_cleanup(p[element].max_torque, 4);

    }
    return 0;
}

int ecat_command_t_decode(const void *buf, int offset, int maxlen, ecat_command_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ecat_command_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ecat_command_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ecat_command_t_decode_cleanup(ecat_command_t *p)
{
    return __ecat_command_t_decode_array_cleanup(p, 1);
}

int __ecat_command_t_clone_array(const ecat_command_t *p, ecat_command_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(p[element].x_des, q[element].x_des, 4);

        __float_clone_array(p[element].y_des, q[element].y_des, 4);

        __float_clone_array(p[element].z_des, q[element].z_des, 4);

        __float_clone_array(p[element].dx_des, q[element].dx_des, 4);

        __float_clone_array(p[element].dy_des, q[element].dy_des, 4);

        __float_clone_array(p[element].dz_des, q[element].dz_des, 4);

        __float_clone_array(p[element].kpx, q[element].kpx, 4);

        __float_clone_array(p[element].kpy, q[element].kpy, 4);

        __float_clone_array(p[element].kpz, q[element].kpz, 4);

        __float_clone_array(p[element].kdx, q[element].kdx, 4);

        __float_clone_array(p[element].kdy, q[element].kdy, 4);

        __float_clone_array(p[element].kdz, q[element].kdz, 4);

        __int32_t_clone_array(p[element].enable, q[element].enable, 4);

        __int32_t_clone_array(p[element].zero_joints, q[element].zero_joints, 4);

        __float_clone_array(p[element].fx_ff, q[element].fx_ff, 4);

        __float_clone_array(p[element].fy_ff, q[element].fy_ff, 4);

        __float_clone_array(p[element].fz_ff, q[element].fz_ff, 4);

        __float_clone_array(p[element].tau_abad_ff, q[element].tau_abad_ff, 4);

        __float_clone_array(p[element].tau_hip_ff, q[element].tau_hip_ff, 4);

        __float_clone_array(p[element].tau_knee_ff, q[element].tau_knee_ff, 4);

        __float_clone_array(p[element].abad_zero_angle, q[element].abad_zero_angle, 4);

        __float_clone_array(p[element].hip_zero_angle, q[element].hip_zero_angle, 4);

        __float_clone_array(p[element].knee_zero_angle, q[element].knee_zero_angle, 4);

        __float_clone_array(p[element].q_des_abad, q[element].q_des_abad, 4);

        __float_clone_array(p[element].q_des_hip, q[element].q_des_hip, 4);

        __float_clone_array(p[element].q_des_knee, q[element].q_des_knee, 4);

        __float_clone_array(p[element].qd_des_abad, q[element].qd_des_abad, 4);

        __float_clone_array(p[element].qd_des_hip, q[element].qd_des_hip, 4);

        __float_clone_array(p[element].qd_des_knee, q[element].qd_des_knee, 4);

        __float_clone_array(p[element].kp_joint_abad, q[element].kp_joint_abad, 4);

        __float_clone_array(p[element].kp_joint_hip, q[element].kp_joint_hip, 4);

        __float_clone_array(p[element].kp_joint_knee, q[element].kp_joint_knee, 4);

        __float_clone_array(p[element].kd_joint_abad, q[element].kd_joint_abad, 4);

        __float_clone_array(p[element].kd_joint_hip, q[element].kd_joint_hip, 4);

        __float_clone_array(p[element].kd_joint_knee, q[element].kd_joint_knee, 4);

        __float_clone_array(p[element].max_torque, q[element].max_torque, 4);

    }
    return 0;
}

ecat_command_t *ecat_command_t_copy(const ecat_command_t *p)
{
    ecat_command_t *q = (ecat_command_t*) malloc(sizeof(ecat_command_t));
    __ecat_command_t_clone_array(p, q, 1);
    return q;
}

void ecat_command_t_destroy(ecat_command_t *p)
{
    __ecat_command_t_decode_array_cleanup(p, 1);
    free(p);
}

int ecat_command_t_publish(lcm_t *lc, const char *channel, const ecat_command_t *p)
{
      int max_data_size = ecat_command_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ecat_command_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _ecat_command_t_subscription_t {
    ecat_command_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void ecat_command_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    ecat_command_t p;
    memset(&p, 0, sizeof(ecat_command_t));
    status = ecat_command_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ecat_command_t!!!\n", status);
        return;
    }

    ecat_command_t_subscription_t *h = (ecat_command_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ecat_command_t_decode_cleanup (&p);
}

ecat_command_t_subscription_t* ecat_command_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    ecat_command_t_handler_t f, void *userdata)
{
    ecat_command_t_subscription_t *n = (ecat_command_t_subscription_t*)
                       malloc(sizeof(ecat_command_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 ecat_command_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg ecat_command_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ecat_command_t_subscription_set_queue_capacity (ecat_command_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int ecat_command_t_unsubscribe(lcm_t *lcm, ecat_command_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ecat_command_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

